#ifndef _EEPROM_MAP_h
#define _EEPROM_MAP_h

#define APP_VERSION_ADDR 0
#define APP_CONFIG_ADDR 10
#define EEPROM_MAP_VER  12
#define TEMP_SENSOR_ADDR1 500
#define TEMP_SENSOR_ADDR2 600
#define TEMP_PROFILE_ADDR 700
#define TEMP_PROFILE_RUNTIME_ADDR 750

#endif
